### PR TITLE
tests written

### LINKED ISSUE #86: [SPIKE] Investigate testing components & setting up a testing library
### Issue Description
Right now the components are only visually inspected by the EM & designers and do not have automated testing for checking functionality. We need to add an appropriate testing system to the component library to make sure our components are lightweight and reusable.

### Acceptance Criteria 
- [ ] A testing library
- [ ] Writeup on how to use/setup tests

### User Story 
Our components are not tested :(

### PR DESCRIPTION
**Pull request by Fattimo**
### Description

Closes #86 

Adds testing into the repository.

### Type of change

✨ Refactor

### How to Test

`yarn`
`yarn test`

### Checklist

- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (EM) have been assigned to this PR

### CODE REVIEW

**Comment by Fattimo** [comment]
Things to consider after this paradigm is approved:
* write 1-2 complicated tests
* restructure the repository such that each component lives in its own directory with its associated story and test file
* add ci testing pipeline

**Comment by therealsharath** [comment]
Is there a way we can automate the "run all tests" question. Like by default run all the tests? 🤔

**Comment by Fattimo** [comment]
https://stackoverflow.com/questions/57968249/create-react-app-configure-jest-run-all-test-files

Although I think it's better as is in terms of the `package.json` script and keeping the test on watch mode for development experience, but probably swapping to test all when putting it up on a CI script

**Comment by therealsharath** [comment]
Sounds good to me. I thought the tests would have a visual output instead of just the terminal, but yeah you're right about keeping it in watch mode as it makes sense from a dev perspective. I was also thinking of setting up a Github action to block pushes if the tests are failing but that can be done later.

**Comment by Fattimo** [comment]
https://storybook.js.org/addons/@storybook/addon-jest

**Pull request merged**
