### PR TITLE
feature(alert): Alert Component

### PR DESCRIPTION
**Pull request by therealsharath**
### Description

Closes https://github.com/GTBitsOfGood/bog-component-library/issues/43

Adds the alert component

### Type of change

🆕 Feature

### Checklist

- [ ]  Code follows design and style guidelines
- [ ]  Code is commented with doc blocks
- [ ]  Latest code has been rebased from base branch (usually `develop`)
- [ ]  Commits follow guidelines (concise, squashed, etc)
- [ ]  Github issues have been linked in relevant commits
- [ ]  Relevant reviewers (EM) have been assigned to this PR

### CODE REVIEW

**Comment by alysonlam** [comment]
Hey Marlene!

- type, iconColor, bgColor, borderColor, looks good
- size: you should be able to set the width and height of the container (px), but the default behavior for the height should be to adjust to the text content. It shouldn't be a choice between large and regular
- hasButton toggle looks good. However, it should be using the tertiary Button component so that the font is the same and, I'm assuming, the behavior would be the same.
- buttonLabel and hasHeader look good
- headerLabel should be Visby CF extra bold 12 px
- alertText should have a size of 12 px and a spacing of 16 px, it doesn't look exactly like that on my screen, but that might just be a rendering thing w the font.
- I think the spacing and padding is off. I've included what it should look like. These values should be adjustable if possible
image
- another parameter, cornerRadius, or something along those lines needs to be added. It should allow devs to change the radius of the corners
- Both icons, message specific and the close x, should be 16 x 16 px. The message specific icon also needs to be replaceable.
- An icon toggle parameter also needs to be created, this wasn't on the Ready for Devs page, that's my bad.

**Review by alysonlam — APPROVED** [review]
Overall looks good! I think the button text needs to be bolded, but it might just be how it's rendering.

Good job and thanks guys :)

**Comment by alysonlam** [comment]
hey hey actually, the button should be using the button component from last semester and should be visby extra bold, not just bold, that's mb.

**Comment by whymarlene** [comment]
> hey hey actually, the button should be using the button component from last semester and should be visby extra bold, not just bold, that's mb.

I am using the button component but I guess the style font didn't transfer. I change that today.

**Comment by therealsharath** [comment]
@alysonlam does it look better now that @whymarlene made changes?

**Comment by alysonlam** [comment]
Font looks good, but the text for the button and header are still not extra-bold for me.

**Pull request merged**
