### PR TITLE
Added sizes to buttons

### PR DESCRIPTION
**Pull request by therealsharath**
### Description

Closes https://github.com/GTBitsOfGood/bog-component-library/issues/39

This change adds the size functionality, which lets the user toggle the size of the button.

#### Large Button
image

#### Medium Button
image

#### Small Button
image

### Type of change

🆕 Feature

### How to Test

Clone the repo, then run `yarn storybook` once the yarn packages are installed. 

### Checklist

- [x]  Code follows design and style guidelines
- [x]  Code is commented with doc blocks
- [x]  Latest code has been rebased from base branch (usually `develop`)
- [x]  Commits follow guidelines (concise, squashed, etc)
- [x]  Github issues have been linked in relevant commits
- [x]  Relevant reviewers (EM) have been assigned to this PR

### CODE REVIEW

**Comment by alysonlam** [comment]
Heyo, there's a few things:
1. the font (Visby CF) should be extra bold
2. the padding looks a bit off for each of the sizes
3. I'm adding ss of the dimensions, keep in mind that each font has a specific height and line height
image
This is also added to the button page in the Figma if you want to look back at it

**Comment by therealsharath** [comment]
@alysonlam I changed the line height to match the Figma docs and the padding to match the commented ss. Any other changes?

**Comment by therealsharath** [comment]
### Large Button
image

### Medium Button
image

### Small Button
image

Idk how useful these are but I can demo these if that helps!

**Review by alysonlam — APPROVED** [review]
Font still looks too thin, but that might be a platform diff. Otherwise, everything else looks good :) As long as the sizing changes were pushed to the other states this is done.

**Pull request merged**
