### PR TITLE
feature(scrolling table of contents ): scrolling navigation implemented

### LINKED ISSUE #148: Scroll Navigation component
### Issue Description
Make a scrolling component for use on our homepage website.

### Resources

Figma: https://www.figma.com/file/DEfDgRT4G9732YxrqTqq8V/OG-BoG-Design-System-(Working-File)?node-id=2982%3A19944

### PR DESCRIPTION
**Pull request by whymarlene**
### Description

Closes #148 

Make a scrolling component for use on our homepage website.

### Type of change
🆕 Feature

### How to Test
 yarn storybook

### Checklist

- [x]  Code follows design and style guidelines
- [x]  Code is commented with doc blocks
- [x]  Latest code has been rebased from base branch (usually `develop`)
- [x]  Commits follow guidelines (concise, squashed, etc)
- [x]  Github issues have been linked in relevant commits
- [x]  Relevant reviewers (EM) have been assigned to this PR

### Progress

- [x] Component
- [x] Theming
- [x] Tests

### CODE REVIEW

**Comment by whymarlene** [comment]
I have to add theming but the essential parts of the navigation are there. Let me know if it needs more customization. 

For now, I am planning on:
- Left/right: for the bar of the active section
- length

Open Question: Should there be sub-sections? If so, what would that look like?(Maybe a future feature?)

**Comment by whymarlene** [comment]
Update:
I couldn't really think of any other tests other than the one I made.

Lmk if there is anything I need to change!

**Comment by therealsharath** [comment]
I'd rename the component to just ScrollNavigation instead of the long name it has rn.

**Review by therealsharath — APPROVED** [review]
LGTM! 🚢  it!

**Pull request merged**
