### PR TITLE
feature(tooltip): Tooltip component

### PR DESCRIPTION
**Pull request by therealsharath**
### Description

Closes https://github.com/GTBitsOfGood/bog-component-library/issues/44

Adds the tooltip component.

### Type of change
🆕 Feature

### How to Test

Running the yarn command and checking the component on the storybook UI

### Checklist

- [x]  Code follows design and style guidelines
- [x]  Code is commented with doc blocks
- [x]  Latest code has been rebased from base branch (usually `develop`)
- [x]  Commits follow guidelines (concise, squashed, etc)
- [x]  Github issues have been linked in relevant commits
- [x]  Relevant reviewers (EM) have been assigned to this PR

### CODE REVIEW

**Comment by therealsharath** [comment]
Everything else looks good to me! All good to 🚢 once you get the designer(s)' approval 🥳

**Comment by alysonlam** [comment]
Hi, could you adjust the way the box behaves in response to the text? Ideally, you should also be able to lock/set the width of the box (excluding the arrow I suppose) so that the text can wrap.

**Comment by alysonlam** [comment]
Also, sorry the capitalized version should not be orange but midnight 500 I believe.

**Comment by alysonlam** [comment]
Text wrapping looks good, however, I think you still need to be able to set the width of the tooltip. Also, the capitalized text should be using the Visby font (extraBold, size 8)

**Comment by jade-law** [comment]
> Text wrapping looks good, however, I think you still need to be able to set the width of the tooltip. Also, the capitalized text should be using the Visby font (extraBold, size 8)

I'm pretty sure the width can be over written without needing to be passed in.

**Pull request merged**
